version: "2"
services:
  todolist:
    container_name: todolist
    image: todolist
    build: .
    command: sh -c "gunicorn  --worker-class gevent --bind 0.0.0.0:8000 todolist.wsgi:application"
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
